### PR TITLE
CDK common library

### PR DESCRIPTION
**Pull request by acarlton**
Prototype integrating Vpc as common shared library package.

### CODE REVIEW

**Comment by dylanvaughn** [comment]
@acarlton awesome!

@helen-kim-oe you should see this - @acarlton pulled all the VPC stuff into a common package:

https://github.com/ordinaryexperts/aws-marketplace-oe-patterns-cdk-common/pull/1

So now we can just drop it into new patterns.

@acarlton I'll approve the PR on the common repo so we can cut a release there. Then we can update the deps on this branch.

**Comment by dylanvaughn** [comment]
https://github.com/ordinaryexperts/aws-marketplace-oe-patterns-cdk-common/pull/1#pullrequestreview-460504735

**Comment by helen-kim-oe** [comment]
@dylanvaughn @acarlton I just looked at the package and the updates here - super clean with those vpc functions  🤩

**Comment by dylanvaughn** [comment]
@acarlton looks good - I think we just need to update the cdk common dependency with the `1.0.0` release I just did:

https://github.com/ordinaryexperts/aws-marketplace-oe-patterns-cdk-common/releases/tag/1.0.0

**Pull request merged**
